package WindowPackages;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.text.DecimalFormat;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.plaf.basic.BasicButtonUI;

import User.Admin;
import User.FileManager;

///rwar

import Payment.IPayment;
import Payment.Purchase;
import Payment.Reserve;
import RealEstate.Block;
import User.FilterSearch;
import User.User;

import javax.swing.table.DefaultTableModel;
import RealEstate.ConcreteHouseFactory;
import RealEstate.HouseFactory;
import RealEstate.IHouse;
import RealEstate.Lot;
import User.Browser;
import java.awt.event.ItemEvent;
import javax.swing.JFrame;
import javax.swing.JRadioButton;
// 



/**
 * 
 *
 * @author Dinel
 */
public class AdminWindow extends javax.swing.JFrame {

    private Admin admin = new Admin("master", "master");
    CardLayout cardLayout;
    DefaultTableModel realestateTb1;
    DefaultTableModel userTb;
    DefaultTableModel lotsTable;
    
    final float maxPrice = 50000000;
    final float minPrice = 5000000;
    final float maxSize = 5000;
    final float minSize = 80;
    float selectedMaxPrice = maxPrice;
    float selectedMinPrice = minPrice;
    float selectedMaxSize = maxSize;
    float selectedMinSize = minSize;
    String selectedLotType = "all";
    String selectedStatus = "all";
    int selectedHouse = 0;
    String type = "client";


    String houseType = "duplex";
    String lotType = "interior";
    int ht = 1;
    int lt = 1;
    int bn = 1;
    int ln = 1;
    
    public AdminWindow() {
        //Setups
        File userFile = new File("./src/TextFiles/users.txt");
        File reFile = new File("./src/TextFiles/realestate.txt");
        admin.setReFm(new FileManager(reFile));
        admin.setUserFm(new FileManager(userFile));
        admin.setHouseFacatory(new ConcreteHouseFactory());
        admin.refreshUsers();
        admin.refreshBlocks();
        admin.setBrowser(new Browser(admin.getBlocks(), new FilterSearch(admin.getBlocks())));
        initComponents();
        
        realestateTb1 = (DefaultTableModel) bTable.getModel();
        userTb = (DefaultTableModel) bTable2.getModel();
        lotsTable = (DefaultTableModel) bTable1.getModel();
        admin.getBrowser().viewListings(realestateTb1, false);
        admin.getBrowser().viewListings(lotsTable, false);
        viewUsers();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizes the window to full screen


        ///Card Layout Switching

        Component [] components = this.getContentPane().getComponents();
        for (Component component : components){
            
             if (component instanceof JButton){
                 ((JButton) component).setUI(new BasicButtonUI());
                 ((JButton) component).setFocusPainted(false);
            }
        }
        cardLayout  = (CardLayout)(pnlCards.getLayout());
    }

    public void viewUsers() {
        userTb.setRowCount(0);
        for(User user: admin.getUsers()) {
            userTb.addRow(new Object[] {String.valueOf(user.getId()), user.getUserName(), user.getPassword(), user.getType().toUpperCase()});
        }
    }

    public void viewLots() {
        DecimalFormat df = new DecimalFormat("#,###.00");
        lotsTable.setRowCount(0);
        for(Block block: admin.getBlocks()) {
            for(Lot lot : block.getLots()) {
                if(lot.getLotNo() == 0 ) {
                    continue;
                }
                System.out.println(lot.getLotNo());
                lotsTable.addRow(new Object[] { String.valueOf(lot.getRealEstateID()), df.format(lot.getPrice()), df.format(lot.getSize()), String.valueOf(block.getBlockNo()), String.valueOf(lot.getLotNo()), lot.getStatus().toUpperCase(), lot.getType().toUpperCase(), String.join(" ", lot.getHouse().getClass().getSimpleName().split("(?=[A-Z])"))  });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        bGroup = new javax.swing.ButtonGroup();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        logOut = new javax.swing.JButton();
        Design1 = new javax.swing.JLabel();
        Design2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewReport = new javax.swing.JButton();
        manageLots = new javax.swing.JButton();
        manageUser = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        pnlCard2 = new javax.swing.JPanel();
        iD = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        pword = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        pWordTextField = new javax.swing.JTextField();
        mUser = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        bTable2 = new javax.swing.JTable();
        adRado = new javax.swing.JRadioButton();
        cliRado = new javax.swing.JRadioButton();
        pnlCard3 = new javax.swing.JPanel();
        bLabel = new javax.swing.JLabel();
        bTextField = new javax.swing.JTextField();
        lLabel = new javax.swing.JLabel();
        lTextField = new javax.swing.JTextField();
        pLabel = new javax.swing.JLabel();
        pTextField = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        updateButton2 = new javax.swing.JButton();
        deleteButton3 = new javax.swing.JButton();
        sLabel = new javax.swing.JLabel();
        sTextField = new javax.swing.JTextField();
        ltLabel = new javax.swing.JLabel();
        htLabel = new javax.swing.JLabel();
        htDrop = new javax.swing.JComboBox<>();
        ltDrop = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bTable1 = new javax.swing.JTable();
        pnlCard1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pDrop = new javax.swing.JComboBox<>();
        Price = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sDrop = new javax.swing.JComboBox<>();
        Size = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lot = new javax.swing.JLabel();
        lDrop = new javax.swing.JComboBox<>();
        hDrop = new javax.swing.JComboBox<>();
        House = new javax.swing.JLabel();
        statDrop = new javax.swing.JComboBox<>();
        statLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Price2 = new javax.swing.JLabel();
        Size1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Lot1 = new javax.swing.JLabel();
        House1 = new javax.swing.JLabel();
        statLabel1 = new javax.swing.JLabel();
        Lot2 = new javax.swing.JLabel();
        Lot3 = new javax.swing.JLabel();
        lotDesc = new javax.swing.JLabel();
        blockDesc = new javax.swing.JLabel();
        priceDesc = new javax.swing.JLabel();
        lotTypeDesc = new javax.swing.JLabel();
        sizeDesc = new javax.swing.JLabel();
        houseDesc = new javax.swing.JLabel();
        statDesc = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bTable = new javax.swing.JTable();
        image = new javax.swing.JLabel();
        description = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new Dimension(1536, 864));

        jSplitPane2.setDividerSize(4);

        jPanel1.setBackground(new java.awt.Color(12, 22, 39));
        jPanel1.setPreferredSize(new java.awt.Dimension(1536, 864));

        logOut.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        logOut.setText("LOG OUT");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        Design1.setBackground(new java.awt.Color(255, 101, 0));
        Design1.setForeground(new java.awt.Color(153, 255, 255));
        Design1.setOpaque(true);

        Design2.setBackground(new java.awt.Color(209, 200, 185));
        Design2.setForeground(new java.awt.Color(153, 255, 255));
        Design2.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(51, 0, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon (new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png")).getImage().getScaledInstance(110, 109, Image.SCALE_DEFAULT)));

        viewReport.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        viewReport.setText("VIEW REPORT");
        viewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportActionPerformed(evt);
            }
        });

        manageLots.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        manageLots.setText("MANAGE LOTS");
        manageLots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLotsActionPerformed(evt);
            }
        });

        manageUser.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        manageUser.setText("MANAGE USER");
        manageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Design1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Design2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(manageUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(viewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(manageLots, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewReport, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(manageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(manageLots, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 595, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addComponent(Design2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Design1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jSplitPane2.setLeftComponent(jPanel1);

        pnlCards.setLayout(new java.awt.CardLayout());

        pnlCard2.setBackground(new java.awt.Color(209, 200, 185));
        pnlCard2.setMaximumSize(new java.awt.Dimension(1536, 864));
        pnlCard2.setPreferredSize(new java.awt.Dimension(1536, 864));

        iD.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        iD.setText("ID");

        userName.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        userName.setText("USERNAME");

        pword.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        pword.setText("PASSWORD");

        addButton.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        mUser.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        mUser.setText("MANAGE USER");

        jScrollPane5.setPreferredSize(new java.awt.Dimension(1536, 864));

        bTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "USERNAME", "PASSWORD", "TYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        bTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTable2MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(bTable2);

        bGroup.add(adRado);
        adRado.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        adRado.setText("ADMIN");
        adRado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cliRadoItemStateChanged(evt);
            }
        });

        bGroup.add(cliRado);
        cliRado.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cliRado.setText("CLIENT");
        cliRado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cliRadoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlCard2Layout = new javax.swing.GroupLayout(pnlCard2);
        pnlCard2.setLayout(pnlCard2Layout);
        pnlCard2Layout.setHorizontalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCard2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addComponent(iD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mUser)
                                    .addGroup(pnlCard2Layout.createSequentialGroup()
                                        .addComponent(userName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCard2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addComponent(pword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCard2Layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlCard2Layout.createSequentialGroup()
                                        .addComponent(cliRado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(adRado)
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCard2Layout.createSequentialGroup()
                                        .addComponent(updateButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteButton)))))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        pnlCard2Layout.setVerticalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(mUser)
                        .addGap(47, 47, 47)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iD)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userName)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pword, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pWordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adRado)
                            .addComponent(cliRado))
                        .addGap(7, 7, 7)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(updateButton)
                            .addComponent(deleteButton)))
                    .addGroup(pnlCard2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard2, "pnlCard2");

        pnlCard3.setBackground(new java.awt.Color(209, 200, 185));

        bLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        bLabel.setText("BLOCK");

        lLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lLabel.setText("LOT");

        lTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lTextFieldActionPerformed(evt);
            }
        });

        pLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        pLabel.setText("PRICE");

        addButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        addButton1.setText("ADD");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        updateButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        updateButton2.setText("UPDATE");
        updateButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButton2ActionPerformed(evt);
            }
        });

        deleteButton3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        deleteButton3.setText("DELETE");
        deleteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton3ActionPerformed(evt);
            }
        });

        sLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        sLabel.setText("SIZE");

        ltLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        ltLabel.setText("LOT TYPE");

        htLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        htLabel.setText("HOUSE TYPE");

        htDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        htDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bungalow", "Modern-Minimalist", "Two-Story", "Duplex", "Town House" }));
        htDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                htDropItemStateChanged(evt);
            }
        });

        ltDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        ltDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corner Lot", "Interior Lot", "Outer Lot" }));
        ltDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ltDropItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel5.setText("MANAGE LOTS");

        jScrollPane4.setPreferredSize(new java.awt.Dimension(1536, 864));

        bTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Price", "SIZE", "BLK. NO.", "LOT NO.", "STATUS", "LOT TYPE", "HOUSE TYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        bTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTable1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(bTable1);

        javax.swing.GroupLayout pnlCard3Layout = new javax.swing.GroupLayout(pnlCard3);
        pnlCard3.setLayout(pnlCard3Layout);
        pnlCard3Layout.setHorizontalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addComponent(htLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(htDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addComponent(bLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lLabel)
                        .addGap(18, 18, 18)
                        .addComponent(lTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlCard3Layout.createSequentialGroup()
                            .addComponent(addButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(updateButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteButton3))
                        .addGroup(pnlCard3Layout.createSequentialGroup()
                            .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sLabel)
                                .addComponent(pLabel))
                            .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlCard3Layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(sTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlCard3Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(pTextField))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6648, Short.MAX_VALUE))
        );
        pnlCard3Layout.setVerticalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(49, 49, 49)
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bLabel)
                            .addComponent(bTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lLabel))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(htLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(htDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton1)
                            .addComponent(updateButton2)
                            .addComponent(deleteButton3)))
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard3, "pnlCard3");

        pnlCard1.setBackground(new java.awt.Color(209, 200, 185));

        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel16.setText("VIEW REPORT");

        pDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        pDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "5,000,000-10,000,000", "10,000,000-15,000,000", "15,000,000-20,000,000", "20,000,000-25,000,000", "25,000,000-30,000,000", "30,000,000-35,000,000", "35,000,000-40,000,000", "40,000,000-45,000,000", "45,000,000-50,000,000" }));
        pDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pDropItemStateChanged(evt);
            }
        });
        pDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDropActionPerformed(evt);
            }
        });

        Price.setBackground(new java.awt.Color(12, 22, 39));
        Price.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(12, 22, 39));
        Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price.setText("PRICE");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("in php");

        sDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        sDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "80-100", "100-200", "200-300", "300-400", "400-500" }));
        sDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sDropItemStateChanged(evt);
            }
        });

        Size.setBackground(new java.awt.Color(12, 22, 39));
        Size.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Size.setForeground(new java.awt.Color(12, 22, 39));
        Size.setText("SIZE");

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("in sqm");

        Lot.setBackground(new java.awt.Color(12, 22, 39));
        Lot.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Lot.setForeground(new java.awt.Color(12, 22, 39));
        Lot.setText("LOT");

        lDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Corner Lot", "Interior Lot", "Outer Lot" }));
        lDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lDropItemStateChanged(evt);
            }
        });

        hDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        hDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Bungalow", "Town House", "Modern-Minimalist", "Duplex", "Two-Story" }));
        hDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hDropItemStateChanged(evt);
            }
        });

        House.setBackground(new java.awt.Color(12, 22, 39));
        House.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        House.setForeground(new java.awt.Color(12, 22, 39));
        House.setText("HOUSE");

        statDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        statDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Available", "Reserved", "Sold" }));
        statDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statDropItemStateChanged(evt);
            }
        });

        statLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        statLabel.setText("STATUS");

        jPanel3.setOpaque(false);

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("in php");

        Price2.setBackground(new java.awt.Color(12, 22, 39));
        Price2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Price2.setForeground(new java.awt.Color(12, 22, 39));
        Price2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price2.setText("PRICE");

        Size1.setBackground(new java.awt.Color(12, 22, 39));
        Size1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Size1.setForeground(new java.awt.Color(12, 22, 39));
        Size1.setText("SIZE");

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("in sqm");

        Lot1.setBackground(new java.awt.Color(12, 22, 39));
        Lot1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Lot1.setForeground(new java.awt.Color(12, 22, 39));
        Lot1.setText("LOT");

        House1.setBackground(new java.awt.Color(12, 22, 39));
        House1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        House1.setForeground(new java.awt.Color(12, 22, 39));
        House1.setText("HOUSE");

        statLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        statLabel1.setText("STATUS");

        Lot2.setBackground(new java.awt.Color(12, 22, 39));
        Lot2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Lot2.setForeground(new java.awt.Color(12, 22, 39));
        Lot2.setText("LOT No:");

        Lot3.setBackground(new java.awt.Color(12, 22, 39));
        Lot3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Lot3.setForeground(new java.awt.Color(12, 22, 39));
        Lot3.setText("Block No:");

        lotDesc.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        blockDesc.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        priceDesc.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        lotTypeDesc.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        sizeDesc.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        houseDesc.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        statDesc.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Price2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(priceDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Size1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sizeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Lot2)
                        .addGap(18, 18, 18)
                        .addComponent(lotDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Lot3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blockDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(statLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Lot1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lotTypeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(House1)
                                .addGap(18, 18, 18)
                                .addComponent(houseDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lot1)
                            .addComponent(lotTypeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(House1))
                    .addComponent(houseDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statLabel1)
                    .addComponent(statDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lot3)
                    .addComponent(blockDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Lot2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Price2)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lotDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Size1)
                        .addComponent(jLabel7))
                    .addComponent(sizeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1536, 864));

        bTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Price", "SIZE", "BLK. NO.", "LOT NO.", "STATUS", "LOT TYPE", "HOUSE TYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        bTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bTable);

        image.setBackground(new java.awt.Color(255, 0, 0));
        image.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("Image");
        image.setOpaque(true);

        description.setBackground(new java.awt.Color(0, 0, 0));
        description.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description.setText("Description");
        description.setOpaque(true);

        javax.swing.GroupLayout pnlCard1Layout = new javax.swing.GroupLayout(pnlCard1);
        pnlCard1.setLayout(pnlCard1Layout);
        pnlCard1Layout.setHorizontalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(Price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addGap(33, 33, 33)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(Size)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(sDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lot)
                            .addComponent(lDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(House)
                            .addComponent(hDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statLabel)
                            .addComponent(statDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        pnlCard1Layout.setVerticalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Size)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Price)
                                    .addComponent(jLabel3))
                                .addGap(2, 2, 2)
                                .addComponent(pDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(statLabel)
                                .addGap(1, 1, 1)
                                .addComponent(statDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(Lot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(House)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard1, "pnlCard1");

        jSplitPane2.setRightComponent(pnlCards);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("images/logout.png"); // not working??

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to log out?", "Log Out",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);

        if (confirm == JOptionPane.YES_OPTION) {
            System.out.println("User logged out.");
            System.exit(0); // Closes the application
        }
    }                                      

    private void viewReportActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard1");
    }                                          

    private void manageLotsActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard3");
    }                                          

    private void manageUserActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        cardLayout.show(pnlCards, "pnlCard2");
        
    }                                          

    private void lTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void pDropItemStateChanged(java.awt.event.ItemEvent evt) {                                       
        // TODO add your handling code here:
        admin.getBrowser().getFilter().resetFilter();
        if(evt.getItem().toString().toLowerCase().equals("all")) {
            selectedMinPrice = minPrice;
            selectedMaxPrice = maxPrice;
        }
        else {
            String[] range = evt.getItem().toString().split("-");
            selectedMinPrice = Float.parseFloat(String.join("", range[0].split(",")));
            selectedMaxPrice = Float.parseFloat(String.join("", range[1].split(",")));
        }

        admin.getBrowser().getFilter().filterStatus(selectedStatus)
        .filterLotType(selectedLotType)
        .filterValues("price", selectedMinPrice, selectedMaxPrice)
        .filterValues("size", selectedMinSize, selectedMaxSize)
        .filterByHouse(selectedHouse);
        admin.getBrowser().viewListings(realestateTb1, true);
    }                                      

    private void pDropActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void sDropItemStateChanged(java.awt.event.ItemEvent evt) {                                       
        // TODO add your handling code here:
        admin.getBrowser().getFilter().resetFilter();
        if(evt.getItem().toString().toLowerCase().equals("all")) {
            selectedMinSize = minSize;
            selectedMaxSize = maxSize;
        }
        else {
            String[] range = evt.getItem().toString().split("-");
            selectedMinSize = Float.parseFloat(String.join("", range[0].split(",")));
            selectedMaxSize = Float.parseFloat(String.join("", range[1].split(",")));
        }

        admin.getBrowser().getFilter().filterStatus(selectedStatus)
        .filterLotType(selectedLotType)
        .filterValues("price", selectedMinPrice, selectedMaxPrice)
        .filterValues("size", selectedMinSize, selectedMaxSize)
        .filterByHouse(selectedHouse);
        admin.getBrowser().viewListings(realestateTb1, true);
    }                                      

    private void lDropItemStateChanged(java.awt.event.ItemEvent evt) {                                       
        // TODO add your handling code here:
        admin.getBrowser().getFilter().resetFilter();  
        String[] item = evt.getItem().toString().toLowerCase().split(" ");
        selectedLotType = item[0];
        admin.getBrowser().getFilter().filterStatus(selectedStatus)
        .filterLotType(selectedLotType)
        .filterValues("price", selectedMinPrice, selectedMaxPrice)
        .filterValues("size", selectedMinSize, selectedMaxSize)
        .filterByHouse(selectedHouse);
        admin.getBrowser().viewListings(realestateTb1, true);
    }                                      

    private void hDropItemStateChanged(java.awt.event.ItemEvent evt) {                                       
        // TODO add your handling code here:
        String houseType = evt.getItem().toString().toLowerCase();
        admin.getBrowser().getFilter().resetFilter();
        if(!houseType.equals("all")) {
            if(houseType.equals("bungalow")) {
                selectedHouse = 1;
            }
            else if(houseType.equals("modern-minimalist")) {
                selectedHouse = 3;
            }
            else if(houseType.equals("two-story")) {
                selectedHouse = 5;
            }
            else if(houseType.equals("duplex")) {
                selectedHouse = 4;
            }
            else if(houseType.equals("town house")) {
                selectedHouse = 2;
            }
        }
        else {
            selectedHouse = 0;
        }

        admin.getBrowser().getFilter().filterStatus(selectedStatus)
        .filterLotType(selectedLotType)
        .filterValues("price", selectedMinPrice, selectedMaxPrice)
        .filterValues("size", selectedMinSize, selectedMaxSize)
        .filterByHouse(selectedHouse);

        admin.getBrowser().viewListings(realestateTb1, true);
    }                                      

    private void statDropItemStateChanged(java.awt.event.ItemEvent evt) {                                          
        selectedStatus = evt.getItem().toString().toLowerCase();
        admin.getBrowser().getFilter().resetFilter();
        admin.getBrowser().getFilter().filterStatus(selectedStatus)
        .filterLotType(selectedLotType)
        .filterValues("price", selectedMinPrice, selectedMaxPrice)
        .filterValues("size", selectedMinSize, selectedMaxSize)
        .filterByHouse(selectedHouse);
        admin.getBrowser().viewListings(realestateTb1, true);
    }                                         

    private void bTableMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        int row = bTable.getSelectedRow();
        int type = 1;
        IHouse house;

        if(realestateTb1.getValueAt(row, 7).toString().equals("Town House")) {
            type = 2;
        }
        if(realestateTb1.getValueAt(row, 7).toString().equals("Duplex")) {
            type = 4;
        }
        if(realestateTb1.getValueAt(row, 7).toString().equals("Two Story")) {
            type = 5;
        }
        if(realestateTb1.getValueAt(row, 7).toString().equals("Bungalow")) {
            type = 1;
        }
        if(realestateTb1.getValueAt(row, 7).toString().equals("Modern Minimalist")) {
            type = 3;
        }

        house = admin.getHouseFacatory().buildHouse(type);
        image.setIcon(new ImageIcon(house.getHouseImage().getImage().getScaledInstance(502, 376, Image.SCALE_DEFAULT)));
        image.setOpaque(false);
        image.setText("");
        description.setText(house.getDescription());
        priceDesc.setText(realestateTb1.getValueAt(row, 1).toString());
        sizeDesc.setText(realestateTb1.getValueAt(row, 2).toString());
        blockDesc.setText(realestateTb1.getValueAt(row, 3).toString());
        lotDesc.setText(realestateTb1.getValueAt(row, 4).toString());
        lotTypeDesc.setText(realestateTb1.getValueAt(row, 5).toString());
        statDesc.setText(realestateTb1.getValueAt(row, 6).toString());
        houseDesc.setText(realestateTb1.getValueAt(row, 7).toString());
    }                                   

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String username = userNameTextField.getText().toString();
        String password = pWordTextField.getText().toString();
        int id = Integer.parseInt(idTextField.getText().toString());
        User user = new User(username, password);
        user.setType(type);
        user.setId(id);

        admin.addUser(user);
        viewUsers();
    
    }                                         

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        String username = userNameTextField.getText().toString();
        String password = pWordTextField.getText().toString();
        int id = Integer.parseInt(idTextField.getText().toString());

        admin.updateUser(id, "username", username);
        admin.updateUser(id, "password", password);
        admin.updateUser(id, "type", type);
        viewUsers();
    }                                            

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        int id = Integer.parseInt(idTextField.getText().toString());
        admin.removeuser(id);
        viewUsers();
    }                                            

    private void cliRadoItemStateChanged(java.awt.event.ItemEvent evt) {                                         
        // TODO add your handling code here:c
        JRadioButton source  = (JRadioButton) evt.getItem();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            type  = source.getText().toString().toLowerCase();
        }
    }                                        

    private void bTable2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int row = bTable2.getSelectedRow();
        userNameTextField.setText(userTb.getValueAt(row, 1).toString());
        pWordTextField.setText(userTb.getValueAt(row, 2).toString());
        idTextField.setText(userTb.getValueAt(row, 0).toString());
        

    }                                    

    private void bTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int row = bTable1.getSelectedRow();
        pTextField.setText(bTable1.getValueAt(row, 1).toString());
        sTextField.setText(bTable1.getValueAt(row, 2).toString());
        bTextField.setText(bTable1.getValueAt(row, 3).toString());
        lTextField.setText(bTable1.getValueAt(row, 4).toString());

        houseType = bTable1.getValueAt(row,7).toString();
        lotType = bTable1.getValueAt(row, 6).toString();

        if(houseType.equals("bungalow")) {
            ht = 1;
        }
        else if(houseType.equals("modern-minimalist")) {
            ht = 3;
        }
        else if(houseType.equals("two-story")) {
            ht = 5;
        }
        else if(houseType.equals("duplex")) {
            ht = 4;
        }
        else if(houseType.equals("town house")) {
            ht = 2;
        }

        if(lotType.equals("corner")) {
            lt = 1;
        }
        else if (lotType.equals("interior")) {
            lt = 2;
        }
        else if (lotType.equals("outer")) {
            lt = 3;
        }
        lDrop.setSelectedIndex(lt -1);
        hDrop.setSelectedIndex(ht -1 );


        int blockNo = Integer.parseInt(bTextField.getText().toString());
        int lotNo = Integer.parseInt(lTextField.getText().toString());
    }                                    

    private void deleteButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        int blockNo = Integer.parseInt(bTextField.getText().toString());
        int lotNo = Integer.parseInt(lTextField.getText().toString());

        admin.removeLot(blockNo, lotNo);
        viewLots();
    }                                             

    private void updateButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        int blockNo = Integer.parseInt(bTextField.getText().toString());
        int lotNo = Integer.parseInt(lTextField.getText().toString());
        String price = String.join((""),pTextField.getText().toString().split((",")));
        String size = sTextField.getText().toString();

        admin.updateLot(blockNo, lotNo, "size", size);
        admin.updateLot(blockNo, lotNo, "lotType", lotType);
        admin.updateLot(blockNo, lotNo, "house", "" + ht);
        admin.updateLot(blockNo, lotNo, "price", price);
        viewLots();
    }                                             

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        Lot lot = new Lot();
        int blockNo = Integer.parseInt(bTextField.getText().toString());
        int lotNo = Integer.parseInt(lTextField.getText().toString());
        String price = pTextField.getText().toString();
        String size = sTextField.getText().toString();

        lot.setType(lotType);
        lot.setLotNo(lotNo);
        lot.setHouse(admin.getHouseFacatory().buildHouse(ht));
        lot.setPrice(Float.parseFloat(String.join("", price.split(","))));
        lot.setSize(Float.parseFloat(String.join("", size.split(","))));
        lot.setStatus("available");
        admin.addLot(blockNo, lot);
        viewLots();

    }                                          

    private void htDropItemStateChanged(java.awt.event.ItemEvent evt) {                                        
        // TODO add your handling code here:
        houseType = evt.getItem().toString();
        if(houseType.equals("bungalow")) {
            ht = 1;
        }
        else if(houseType.equals("modern-minimalist")) {
            ht = 3;
        }
        else if(houseType.equals("two-story")) {
            ht = 5;
        }
        else if(houseType.equals("duplex")) {
            ht = 4;
        }
        else if(houseType.equals("town house")) {
            ht = 2;
        }
    }                                       

    private void ltDropItemStateChanged(java.awt.event.ItemEvent evt) {                                        
        // TODO add your handling code here:
        lotType = evt.getItem().toString().split(" ")[0].toLowerCase();
        if(lotType.equals("corner")) {
            lt = 1;
        }
        else if (lotType.equals("interior")) {
            lt = 2;
        }
        else if (lotType.equals("outer")) {
            lt = 3;
        }


    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //? I don't know what this does
                //new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Design1;
    private javax.swing.JLabel Design2;
    private javax.swing.JLabel House;
    private javax.swing.JLabel House1;
    private javax.swing.JLabel Lot;
    private javax.swing.JLabel Lot1;
    private javax.swing.JLabel Lot2;
    private javax.swing.JLabel Lot3;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Price2;
    private javax.swing.JLabel Size;
    private javax.swing.JLabel Size1;
    private javax.swing.JRadioButton adRado;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.ButtonGroup bGroup;
    private javax.swing.JLabel bLabel;
    private javax.swing.JTable bTable;
    private javax.swing.JTable bTable1;
    private javax.swing.JTable bTable2;
    private javax.swing.JTextField bTextField;
    private javax.swing.JLabel blockDesc;
    private javax.swing.JRadioButton cliRado;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton deleteButton3;
    private javax.swing.JLabel description;
    private javax.swing.JComboBox<String> hDrop;
    private javax.swing.JLabel houseDesc;
    private javax.swing.JComboBox<String> htDrop;
    private javax.swing.JLabel htLabel;
    private javax.swing.JLabel iD;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JComboBox<String> lDrop;
    private javax.swing.JLabel lLabel;
    private javax.swing.JTextField lTextField;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel lotDesc;
    private javax.swing.JLabel lotTypeDesc;
    private javax.swing.JComboBox<String> ltDrop;
    private javax.swing.JLabel ltLabel;
    private javax.swing.JLabel mUser;
    private javax.swing.JButton manageLots;
    private javax.swing.JButton manageUser;
    private javax.swing.JComboBox<String> pDrop;
    private javax.swing.JLabel pLabel;
    private javax.swing.JTextField pTextField;
    private javax.swing.JTextField pWordTextField;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JLabel priceDesc;
    private javax.swing.JLabel pword;
    private javax.swing.JComboBox<String> sDrop;
    private javax.swing.JLabel sLabel;
    private javax.swing.JTextField sTextField;
    private javax.swing.JLabel sizeDesc;
    private javax.swing.JLabel statDesc;
    private javax.swing.JComboBox<String> statDrop;
    private javax.swing.JLabel statLabel;
    private javax.swing.JLabel statLabel1;
    private javax.swing.JButton updateButton;
    private javax.swing.JButton updateButton2;
    private javax.swing.JLabel userName;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JButton viewReport;
    // End of variables declaration                   
}
