package WindowPackages;

import User.FileManager;
import User.FilterSearch;

//import Managers.RealEstateManager;
//import MyLibs.RealEstate;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;

import RealEstate.Block;
import RealEstate.ConcreteHouseFactory;
import RealEstate.HouseFactory;
import RealEstate.Lot;
import User.Admin;
import User.Browser;
import User.Client;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dinel
 */
public class ClientWindow2 extends javax.swing.JFrame {

    CardLayout cardLayout;
    Admin admin = new Admin("Master", "Master");
    Client client = new Client("Client", "client");
    DefaultTableModel tb;
    final float maxPrice = 50000000;
    final float minPrice = 5000000;
    final float maxSize = 5000;
    final float minsize = 80;
    float selectMaxPrice = maxPrice;
    float selectedMinPrice = minPrice;
    float selectedMaxSize = maxSize;
    float slectedMinsize = minsize;
    String selectedLotType = "interior";
    String selectedStatus = "available";
    int selectedHouse = 0;

    public ClientWindow2() {
        admin.setReFm(new FileManager(new File("./src/TextFiles/realestate.txt")));
        admin.setHouseFacatory(new ConcreteHouseFactory());
        admin.refreshBlocks();
        client.setBrowser(new Browser());
        client.getBrowser().setListings(admin.getBlocks());
        client.getBrowser().setFilter(new FilterSearch(client.getBrowser().getListings()));

        initComponents();
        tb = (DefaultTableModel) bTable.getModel();
        client.getBrowser().viewListings(tb, false);
       
       Component [] components = this.getContentPane().getComponents();
       for (Component component : components)
       {
           boolean isButton = component instanceof JButton;
           if(isButton)
           {
               ((JButton) component).setUI(new BasicButtonUI());
               ((JButton) component).setFocusPainted(false);
           }
       }
       cardLayout = (CardLayout)(pnlCards.getLayout());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        logOut = new javax.swing.JButton();
        vBar1 = new javax.swing.JLabel();
        vBar = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        pnlCards = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        Price = new javax.swing.JLabel();
        Size = new javax.swing.JLabel();
        House = new javax.swing.JLabel();
        Lot = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bTable = new javax.swing.JTable();
        buy = new javax.swing.JButton();
        reserve = new javax.swing.JButton();
        sDrop = new javax.swing.JComboBox<>();
        hDrop = new javax.swing.JComboBox<>();
        lDrop = new javax.swing.JComboBox<>();
        pDrop = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        statLabel = new javax.swing.JLabel();
        statDrop = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        pnlCard2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(1536, 864));
        setSize(new java.awt.Dimension(1536, 864));

        jSplitPane1.setDividerSize(4);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1536, 864));

        jPanel1.setBackground(new java.awt.Color(12, 22, 39));
        jPanel1.setPreferredSize(new java.awt.Dimension(1536, 864));

        logOut.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        logOut.setText("LOG OUT");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        vBar1.setBackground(new java.awt.Color(255, 101, 0));
        vBar1.setForeground(new java.awt.Color(153, 255, 255));
        vBar1.setOpaque(true);

        vBar.setBackground(new java.awt.Color(209, 200, 185));
        vBar.setForeground(new java.awt.Color(153, 255, 255));
        vBar.setOpaque(true);

        logo.setBackground(new java.awt.Color(51, 0, 255));
        logo.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("LOGO");
        logo.setOpaque(true);

        browseButton.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        browseButton.setText("BROWSE");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(vBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(vBar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(vBar, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(vBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logOut.getAccessibleContext().setAccessibleName("BrowsingTab");

        jSplitPane1.setLeftComponent(jPanel1);

        pnlCards.setPreferredSize(new java.awt.Dimension(1536, 864));
        pnlCards.setLayout(new java.awt.CardLayout());

        pnlCard1.setBackground(new java.awt.Color(209, 200, 185));
        pnlCard1.setPreferredSize(new Dimension(1536 , 864));

        Price.setBackground(new java.awt.Color(12, 22, 39));
        Price.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Price.setForeground(new java.awt.Color(12, 22, 39));
        Price.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Price.setText("PRICE");

        Size.setBackground(new java.awt.Color(12, 22, 39));
        Size.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Size.setForeground(new java.awt.Color(12, 22, 39));
        Size.setText("SIZE");

        House.setBackground(new java.awt.Color(12, 22, 39));
        House.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        House.setForeground(new java.awt.Color(12, 22, 39));
        House.setText("HOUSE");

        Lot.setBackground(new java.awt.Color(12, 22, 39));
        Lot.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Lot.setForeground(new java.awt.Color(12, 22, 39));
        Lot.setText("LOT");

        image.setBackground(new java.awt.Color(255, 0, 0));
        image.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image.setText("Image");
        image.setOpaque(true);

        description.setBackground(new java.awt.Color(0, 0, 0));
        description.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 255));
        description.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        description.setText("Description");
        description.setOpaque(true);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1536, 864));

        bTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Price", "SIZE", "BLK. NO.", "LOT NO.", "STATUS", "LOT TYPE", "HOUSE TYPE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        bTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bTable);

        buy.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        buy.setText("Buy");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        reserve.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        reserve.setText("Reserve");
        reserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveActionPerformed(evt);
            }
        });

        sDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        sDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "80-100", "100-200", "200-300", "300-400", "400-500" }));
        sDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sDropItemStateChanged(evt);
            }
        });

        hDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        hDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bungalow", "Town House", "Modern-Minimalist", "Duplex", "Two-Story" }));
        hDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                hDropItemStateChanged(evt);
            }
        });

        lDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        lDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corner Lot", "Interior Lot", "Outer Lot" }));
        lDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lDropItemStateChanged(evt);
            }
        });
        lDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lDropActionPerformed(evt);
            }
        });

        pDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        pDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5,000,000-10,000,000", "10,000,000-15,000,000", "15,000,000-20,000,000", "20,000,000-25,000,000", "25,000,000-30,000,000", "30,000,000-35,000,000", "35,000,000-40,000,000", "40,000,000-45,000,000", "45,000,000-50,000,000" }));
        pDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pDropItemStateChanged(evt);
            }
        });
        pDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDropActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("in sqm");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("in php");

        statLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        statLabel.setText("STATUS");

        statDrop.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        statDrop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Reserved", "Sold" }));
        statDrop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                statDropItemStateChanged(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel16.setText("BROWSE");

        javax.swing.GroupLayout pnlCard1Layout = new javax.swing.GroupLayout(pnlCard1);
        pnlCard1.setLayout(pnlCard1Layout);
        pnlCard1Layout.setHorizontalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(Size)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(sDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addComponent(Price)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(House)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Lot)
                                    .addComponent(hDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statLabel)
                            .addComponent(statDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(179, 179, 179))
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCard1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(description, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(image, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlCard1Layout.createSequentialGroup()
                                        .addComponent(reserve)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
        );
        pnlCard1Layout.setVerticalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCard1Layout.createSequentialGroup()
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Price)
                                    .addComponent(jLabel3))
                                .addGap(2, 2, 2)
                                .addComponent(pDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Size)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCard1Layout.createSequentialGroup()
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(House)
                                    .addComponent(statLabel))
                                .addGap(1, 1, 1)
                                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Lot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reserve, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard1, "BrowsingTab");

        pnlCard2.setBackground(new java.awt.Color(51, 0, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO OUR REAL ESTATE");

        javax.swing.GroupLayout pnlCard2Layout = new javax.swing.GroupLayout(pnlCard2);
        pnlCard2.setLayout(pnlCard2Layout);
        pnlCard2Layout.setHorizontalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCard2Layout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        pnlCard2Layout.setVerticalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard2, "PurchasedTab");

        jSplitPane1.setRightComponent(pnlCards);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        // TODO add your handling code here:        
        ImageIcon icon = new ImageIcon("images/logout.png"); // not working??

        int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to log out?", "Log Out", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);

        if (confirm == JOptionPane.YES_OPTION) {
            System.out.println("User logged out.");
            System.exit(0); // Closes the application
        } 
    }//GEN-LAST:event_logOutActionPerformed

    private void reserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reserveActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        // This does nothing :-(
        //@Dinel

    }//GEN-LAST:event_browseButtonActionPerformed

    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyActionPerformed

    private void sDropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sDropItemStateChanged
        // TODO add your handling code here:
        String[] range = evt.getItem().toString().split("-");
        System.out.println(range[0]);
        System.out.println(range[1]);
        slectedMinsize = Float.parseFloat(String.join("", range[0].split(",")));
        selectedMaxSize = Float.parseFloat(String.join("", range[1].split(",")));
        client.getBrowser().getFilter().clearFilter();
        client.getBrowser().getFilter().filterByLotStatus(selectedStatus).filterByValues("price", selectedMinPrice, selectMaxPrice).filterByValues("size", slectedMinsize, selectedMaxSize).filterByLotType(selectedLotType).filterByHouse(selectedHouse);
        client.getBrowser().viewListings(tb, true);
    }//GEN-LAST:event_sDropItemStateChanged

    private void hDropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_hDropItemStateChanged
        // TODO add your handling code here:
        //  Bungalow", "Modern-Minimalist", "Two-Story", "Duplex", "Town House"
        String houseType = evt.getItem().toString().toLowerCase();
        if(houseType.equals("bungalow")) {
            selectedHouse = 1;
        }
        else if(houseType.equals("modern-minimalist")) {
            selectedHouse = 3;
        }
        else if(houseType.equals("two-story")) {
            selectedHouse = 5;
        }
        else if(houseType.equals("duplex")) {
            selectedHouse = 4;
        }
        else if(houseType.equals("town house")) {
            selectedHouse = 2;
        }

        
        client.getBrowser().getFilter().clearFilter();
        client.getBrowser().getFilter().filterByLotStatus(selectedStatus).filterByValues("price", selectedMinPrice, selectMaxPrice).filterByValues("size", slectedMinsize, selectedMaxSize).filterByLotType(selectedLotType).filterByHouse(selectedHouse);
        client.getBrowser().viewListings(tb, true);        
    }//GEN-LAST:event_hDropItemStateChanged

    private void lDropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lDropItemStateChanged
        // TODO add your handling code here:
        String[] item = evt.getItem().toString().toLowerCase().split(" ");
        selectedLotType = item[0];
        client.getBrowser().getFilter().clearFilter();
        client.getBrowser().getFilter().filterByLotStatus(selectedStatus).filterByValues("price", selectedMinPrice, selectMaxPrice).filterByValues("size", slectedMinsize, selectedMaxSize).filterByLotType(selectedLotType).filterByHouse(selectedHouse);
        client.getBrowser().viewListings(tb, true);
    }//GEN-LAST:event_lDropItemStateChanged

    private void bTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bTableMouseClicked

    private void pDropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pDropItemStateChanged
        // TODO add your handling code here:
        String[] range = evt.getItem().toString().split("-");
        System.out.println(range[0]);
        System.out.println(range[1]);
        selectedMinPrice = Float.parseFloat(String.join("", range[0].split(",")));
        selectMaxPrice = Float.parseFloat(String.join("", range[1].split(",")));
        client.getBrowser().getFilter().clearFilter();
        client.getBrowser().getFilter().filterByLotStatus(selectedStatus).filterByValues("price", selectedMinPrice, selectMaxPrice).filterByValues("size", slectedMinsize, selectedMaxSize).filterByLotType(selectedLotType).filterByHouse(selectedHouse);
        client.getBrowser().viewListings(tb, true);
    }//GEN-LAST:event_pDropItemStateChanged

    private void pDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pDropActionPerformed

    private void lDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lDropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lDropActionPerformed

    private void statDropItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_statDropItemStateChanged
        selectedStatus = evt.getItem().toString().toLowerCase();
        client.getBrowser().getFilter().clearFilter();
        client.getBrowser().getFilter().filterByLotStatus(selectedStatus).filterByValues("price", selectedMinPrice, selectMaxPrice).filterByValues("size", slectedMinsize, selectedMaxSize).filterByLotType(selectedLotType).filterByHouse(selectedHouse);
        client.getBrowser().viewListings(tb, true);
        
    }//GEN-LAST:event_statDropItemStateChanged


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientWindow2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientWindow2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel House;
    private javax.swing.JLabel Lot;
    private javax.swing.JLabel Price;
    private javax.swing.JLabel Size;
    private javax.swing.JTable bTable;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton buy;
    private javax.swing.JLabel description;
    private javax.swing.JComboBox<String> hDrop;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JComboBox<String> lDrop;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> pDrop;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JButton reserve;
    private javax.swing.JComboBox<String> sDrop;
    private javax.swing.JComboBox<String> statDrop;
    private javax.swing.JLabel statLabel;
    private javax.swing.JLabel vBar;
    private javax.swing.JLabel vBar1;
    // End of variables declaration//GEN-END:variables
}
